
#  security:
#    oauth2:
#      client:
#        registration:
#            github:
#              client-id: Iv1.e96017fb31cbe8ec
#              client-secret: 2a72f2f0613a53ee065b206b64f71b97c8562509
#            google:
#              client-id: 792848395836-87lstgiofvt08baktff8gec54iv66gi4.apps.googleusercontent.com
#              client-secret: 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

server:
  port: 8081

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
#  data:
#    mongodb:
#      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}${MONGODB_CLUSTER}
#      database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG

